spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
        use_sql_comments: true
        default_schema: public
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type: debug

server:
  port: 18123

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:imports}

spring.datasource.hikari.minimum-idle: 0
spring.datasource.hikari.initialization-fail-timeout: -1
spring.sql.init.continue-on-error: true
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: none
spring.jpa.defer-datasource-initialization: true
spring.datasource.type: org.springframework.jdbc.datasource.SimpleDriverDataSource
spring.jpa.open-in-view: false
spring.jpa.hibernate.enable_lazy_load_no_trans: true
